### ISSUE TITLE
Some questions about iRFDS Loss

### ISSUE THREAD

**Issue by bookkkker** [yangxiaofeng/rectified_flow_prior#8]
![image](https://github.com/user-attachments/assets/9a80a80f-7d5d-48bd-8697-fbeb56aa403c)
Sorry to disturb you again. According to the formula，it looks like there are some differences between the formula and the code.
![image](https://github.com/user-attachments/assets/d59f325a-0789-432d-a226-795d50bd283d)
if noise_to_optimize represents ε，latents represents x，Is the order of ε and x wrong in the code? Thank you for your request.

**Comment by yangxiaofeng** [comment]
Thank you for your question! The screenshot you provided is from an earlier version of our paper. The formulas in that version were derived from the rectified-flow theory (Liu et al., 2022). However, SD3 uses slightly different formulas, based on Lipman et al. (2022), and that's why there is a difference.

In our latest version (please see the new paper from arxiv), we have derived the formulas using the new Stochastic Interpolants framework. This approach naturally supports both SD3 and Instaflow theories.

**Comment by bookkkker** [comment]
![670011f481c2687e5b0e8999964c612](https://github.com/user-attachments/assets/f25d37f9-46df-43e5-a954-24b0a93f41d2)
![9aba86c8c5110f63af3e90b72537e5d](https://github.com/user-attachments/assets/c403aabb-07fe-4b8c-aabc-75b67dae11a1)
The above is the image after iRFDS-sd3, the prompt is "a photo of a corgi". I choose the last latent after optimization and the same prompt to generate the inversion image, the bottom is the original image.They seem to be quite different. Can you give me some advices?Thank you！(I didn't change your code)

**Comment by yangxiaofeng** [comment]
Hi, I believe the result is quite expected. Based on my experience, SD3 doesn't perform very well in terms of iRFDS (as also shown in our paper, where SD3 lags behind Instaflow). One reason is that SD3 hasn’t been fine-tuned with reflow. Another reason is that SD3 uses a 16-channel latent space, which makes it harder to optimize.

**Comment by bookkkker** [comment]
Thank you!! By the way,recently I also try to use your method to do Flux inversion, but failed.Looking forward to your updates!
